"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.inventoryAssets = void 0;
const index_1 = require("@shared/index");
var inventoryAssets;
(function (inventoryAssets) {
    inventoryAssets.items = {
        ["hat" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HAT */]: {
            type: "hat" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HAT */,
            typeCategory: 1 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP */,
            hash: "",
            key: "",
            quality: -1,
            image: "hat.svg",
            render: "hat.svg",
            name: "Hat",
            description: "Headgear.",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            modelHash: "prop_proxy_hat_01",
            gender: null,
            isPlaced: false
        },
        ["mask" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MASK */]: {
            type: "mask" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MASK */,
            typeCategory: 0 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING */,
            hash: "",
            key: "",
            quality: -1,
            image: "mask.svg",
            render: "mask.svg",
            name: "Mask",
            description: "Completely hides your face.",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "p_orleans_mask_s"
        },
        ["glasses" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GLASSES */]: {
            type: "glasses" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GLASSES */,
            typeCategory: 1 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP */,
            hash: "",
            key: "",
            quality: -1,
            image: "glasses.svg",
            render: "glasses.svg",
            name: "Glasses",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_cs_sol_glasses"
        },
        ["earRings" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_EARRINGS */]: {
            type: "earRings" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_EARRINGS */,
            typeCategory: 1 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP */,
            hash: "",
            key: "",
            quality: -1,
            image: "earRings.svg",
            render: "earRings.svg",
            name: "Earrings",
            description: "",
            count: 1,
            weight: 0.05,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "p_tmom_earrings_s"
        },
        ["chain" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CHAIN */]: {
            type: "chain" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CHAIN */,
            typeCategory: 1 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP */,
            hash: "",
            key: "",
            quality: -1,
            image: "chain.svg",
            render: "chain.svg",
            name: "Chain",
            description: "Perfect accessory to flex.",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        ["tShirt" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TSHIRT */]: {
            type: "tShirt" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TSHIRT */,
            typeCategory: 0 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING */,
            hash: "",
            key: "",
            quality: -1,
            image: "tShirt.svg",
            render: "tShirt.svg",
            name: "T-shirt",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_tshirt_01"
        },
        ["top" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TOP */]: {
            type: "top" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TOP */,
            typeCategory: 0 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING */,
            hash: "",
            key: "",
            quality: -1,
            image: "top.svg",
            render: "top.svg",
            name: "Jacket",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_shirt_01"
        },
        ["armour" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ARMOUR */]: {
            type: "armour" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ARMOUR */,
            typeCategory: 0 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING */,
            hash: "",
            key: "",
            quality: -1,
            image: "armour.svg",
            render: "armour.svg",
            name: "Body armor",
            description: "Provides protection for the upper torso.",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_bodyarmour_03",
            amount: 100
        },
        ["watch" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_WATCH */]: {
            type: "watch" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_WATCH */,
            typeCategory: 1 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP */,
            hash: "",
            key: "",
            quality: -1,
            image: "watch.svg",
            render: "watch.svg",
            name: "Watch",
            description: "Wristwatch.",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        ["gloves" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GLOVES */]: {
            type: "gloves" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GLOVES */,
            typeCategory: 0 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING */,
            hash: "",
            key: "",
            quality: -1,
            image: "gloves.svg",
            render: "gloves.svg",
            name: "Gloves",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        ["pants" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PANTS */]: {
            type: "pants" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PANTS */,
            typeCategory: 0 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING */,
            hash: "",
            key: "",
            quality: -1,
            image: "pants.svg",
            render: "pants.svg",
            name: "Pants",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "bkr_prop_duffel_bag_01a"
        },
        ["shoes" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SHOES */]: {
            type: "shoes" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SHOES */,
            typeCategory: 0 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING */,
            hash: "",
            key: "",
            quality: -1,
            image: "shoes.svg",
            render: "shoes.svg",
            name: "Shoes",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 10,
            options: ["putOn", "drop", "trade"],
            gender: null,
            isPlaced: false,
            modelHash: "v_res_fa_shoebox4"
        },
        ["backpack" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BACKPACK */]: {
            type: "backpack" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BACKPACK */,
            typeCategory: 0 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING */,
            hash: "",
            key: "",
            quality: 0,
            image: "backpack.svg",
            render: "backpack.svg",
            name: "Backpack",
            description: "Increases inventory capacity.",
            count: 1,
            weight: 5,
            maxStack: 1,
            isPlaced: false,
            options: ["open", "putOn", "drop", "trade"],
            gender: null,
            modelHash: "vw_prop_vw_backpack_01a",
            items: {
                0: null,
                1: null,
                2: null,
                3: null,
                4: null,
                5: null,
                6: null,
                7: null,
                8: null,
                9: null,
                10: null,
                11: null,
                12: null,
                13: null,
                14: null,
                15: null,
                16: null,
                17: null,
                18: null,
                19: null,
                20: null,
                21: null,
                22: null,
                23: null
            }
        },
        ["weapon_dagger" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_DAGGER */]: {
            type: "weapon_dagger" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_DAGGER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "dagger.svg",
            render: "dagger.svg",
            name: "dagger",
            description: "",
            count: 1,
            weight: 0.6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_dagger"
        },
        ["weapon_bat" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BAT */]: {
            type: "weapon_bat" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BAT */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "bat.svg",
            render: "bat.svg",
            name: "bat",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_bat"
        },
        ["weapon_bottle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BOTTLE */]: {
            type: "weapon_bottle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BOTTLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "bottle.svg",
            render: "bottle.svg",
            name: "bottle",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_bottle"
        },
        ["weapon_crowbar" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CROWBAR */]: {
            type: "weapon_crowbar" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CROWBAR */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "crowbar.svg",
            render: "crowbar.svg",
            name: "crowbar",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_crowbar"
        },
        ["weapon_flashlight" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_FLASHLIGHT */]: {
            type: "weapon_flashlight" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_FLASHLIGHT */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "flashlight.svg",
            render: "flashlight.svg",
            name: "flashlight",
            description: "",
            count: 1,
            weight: 0.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_FLASHLIGHT"
        },
        ["weapon_golfclub" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GOLFCLUB */]: {
            type: "weapon_golfclub" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GOLFCLUB */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "golfclub.svg",
            render: "golfclub.svg",
            name: "golfclub",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_gclub"
        },
        ["weapon_hammer" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HAMMER */]: {
            type: "weapon_hammer" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HAMMER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "hammer.svg",
            render: "hammer.svg",
            name: "hammer",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_hammer"
        },
        ["weapon_hatchet" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HATCHET */]: {
            type: "weapon_hatchet" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HATCHET */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "hatchet.svg",
            render: "hatchet.svg",
            name: "hatchet",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_hatchet"
        },
        ["weapon_knuckleduster" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_KNUCKLEDUSTER */]: {
            type: "weapon_knuckleduster" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_KNUCKLEDUSTER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "knuckle.svg",
            render: "knuckle.svg",
            name: "knuckle",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_KNUCKLE"
        },
        ["weapon_knife" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_KNIFE */]: {
            type: "weapon_knife" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_KNIFE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "knife.svg",
            render: "knife.svg",
            name: "knife",
            description: "",
            count: 1,
            weight: 0.6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_knife_01"
        },
        ["weapon_machete" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MACHETE */]: {
            type: "weapon_machete" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MACHETE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "machete.svg",
            render: "machete.svg",
            name: "machete",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_w_me_machette"
        },
        ["weapon_switchblade" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SWITCHBLADE */]: {
            type: "weapon_switchblade" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SWITCHBLADE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "switchblade.svg",
            render: "switchblade.svg",
            name: "switchblade",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_SWITCHBLADE"
        },
        ["weapon_nightstick" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_NIGHTSTICK */]: {
            type: "weapon_nightstick" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_NIGHTSTICK */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "nightstick.svg",
            render: "nightstick.svg",
            name: "nightstick",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_me_nightstick"
        },
        ["weapon_wrench" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_WRENCH */]: {
            type: "weapon_wrench" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_WRENCH */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "wrench.svg",
            render: "wrench.svg",
            name: "wrench",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_tool_wrench"
        },
        ["weapon_battleaxe" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BATTLEAXE */]: {
            type: "weapon_battleaxe" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BATTLEAXE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "battleaxe.svg",
            render: "battleaxe.svg",
            name: "battleaxe",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_fireaxe"
        },
        ["weapon_poolcue" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_POOLCUE */]: {
            type: "weapon_poolcue" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_POOLCUE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "poolcue.svg",
            render: "poolcue.svg",
            name: "poolcue",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_pool_cue"
        },
        ["weapon_pistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL */]: {
            type: "weapon_pistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "pistol.svg",
            render: "pistol.svg",
            name: "Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_pistol_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL_MK2 */]: {
            type: "weapon_pistol_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL_MK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "pistolmk2.svg",
            render: "pistolmk2.svg",
            name: "MK2 Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_combatpistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATPISTOL */]: {
            type: "weapon_combatpistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "combatpistol.svg",
            render: "combatpistol.svg",
            name: "Combat Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_combatpistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_appistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_APPISTOL */]: {
            type: "weapon_appistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_APPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "appistol.svg",
            render: "appistol.svg",
            name: "Pistol AP",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_appistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_stungun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_STUNGUN */]: {
            type: "weapon_stungun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_STUNGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "stungun.svg",
            render: "stungun.svg",
            name: "Stungun",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_stungun"
        },
        ["weapon_pistol50" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL50 */]: {
            type: "weapon_pistol50" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL50 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "pistol50.svg",
            render: "pistol50.svg",
            name: "Pistol 50",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol50",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_snspistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SNSPISTOL */]: {
            type: "weapon_snspistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SNSPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "snspistol.svg",
            render: "snspistol.svg",
            name: "SNS Pistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_sns_pistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_snspistol_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SNSPISTOL_MK2 */]: {
            type: "weapon_snspistol_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SNSPISTOL_MK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "snspistolmk2.svg",
            render: "snspistolmk2.svg",
            name: "MK2 SNS Pistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_sns_pistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_heavypistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYPISTOL */]: {
            type: "weapon_heavypistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "heavypistol.svg",
            render: "heavypistol.svg",
            name: "Heavy Pistol",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_heavypistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_vintagepistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_VINTAGEPISTOL */]: {
            type: "weapon_vintagepistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_VINTAGEPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "vintagepistol.svg",
            render: "vintagepistol.svg",
            name: "Vintage Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_vintage_pistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_flaregun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_FLAREGUN */]: {
            type: "weapon_flaregun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_FLAREGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "flaregun.svg",
            render: "flaregun.svg",
            name: "Flaregun",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_flaregun",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_marksmanpistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANPISTOL */]: {
            type: "weapon_marksmanpistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanpistol.svg",
            render: "marksmanpistol.svg",
            name: "Marksman Pistol",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_marksmanpistol ",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_revolver" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_REVOLVER */]: {
            type: "weapon_revolver" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_REVOLVER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "revolver.svg",
            render: "heavyrevolver.svg",
            name: "revolver",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_revolver",
            ammoType: "REVOLVERAMMO"
        },
        ["weapon_revolvermk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_REVOLVERMK2 */]: {
            type: "weapon_revolvermk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_REVOLVERMK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "revolvermk2.svg",
            render: "revolvermk2.svg",
            name: "revolvermk2",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_revolver",
            ammoType: "REVOLVERAMMO"
        },
        ["weapon_doubleaction" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_DOUBLEACTION */]: {
            type: "weapon_doubleaction" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_DOUBLEACTION */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "doubleaction.svg",
            render: "doubleaction.svg",
            name: "doubleaction",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "REVOLVERAMMO"
        },
        ["weapon_raypistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RAYPISTOL */]: {
            type: "weapon_raypistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RAYPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "raypistol.svg",
            render: "raypistol.svg",
            name: "raypistol",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_ceramicpistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CERAMICPISTOL */]: {
            type: "weapon_ceramicpistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CERAMICPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "ceramicpistol.svg",
            render: "ceramicpistol.svg",
            name: "ceramicpistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_navyrevolver" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_NAVYREVOLVER */]: {
            type: "weapon_navyrevolver" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_NAVYREVOLVER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "navyrevolver.svg",
            render: "navyrevolver.svg",
            name: "navyrevolver",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "REVOLVERAMMO"
        },
        ["weapon_gadgetpistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GADGETPISTOL */]: {
            type: "weapon_gadgetpistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GADGETPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "gadgetpistol.svg",
            render: "gadgetpistol.svg",
            name: "gadgetpistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_heavypistol",
            ammoType: "PISTOLAMMO"
        },
        ["weapon_stungunmp" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_STUNGUNMP */]: {
            type: "weapon_stungunmp" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_STUNGUNMP */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "stungun.svg",
            render: "stungun.svg",
            name: "stungun",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_stungun"
        },
        ["weapon_microsmg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MICROSMG */]: {
            type: "weapon_microsmg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MICROSMG */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "microsmg.svg",
            render: "microsmg.svg",
            name: "microsmg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sb_microsmg",
            ammoType: "SMGAMMO"
        },
        ["weapon_smg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SMG */]: {
            type: "weapon_smg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SMG */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "smg.svg",
            render: "smg.svg",
            name: "smg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sb_smg",
            ammoType: "SMGAMMO"
        },
        ["weapon_smg_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SMG_MK2 */]: {
            type: "weapon_smg_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SMG_MK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "smgmk2.svg",
            render: "smgmk2.svg",
            name: "smgmk2",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sb_smg",
            ammoType: "SMGAMMO"
        },
        ["weapon_assaultsmg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTSMG */]: {
            type: "weapon_assaultsmg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTSMG */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultsmg.svg",
            render: "assaultsmg.svg",
            name: "assaultsmg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sb_assaultsmg",
            ammoType: "SMGAMMO"
        },
        ["weapon_combatpdw" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATPDW */]: {
            type: "weapon_combatpdw" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATPDW */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "combatpdw.svg",
            render: "combatpdw.svg",
            name: "combatpdw",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_COMBATPDW",
            ammoType: "SMGAMMO"
        },
        ["weapon_machinepistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MACHINEPISTOL */]: {
            type: "weapon_machinepistol" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MACHINEPISTOL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "machinepistol.svg",
            render: "machinepistol.svg",
            name: "machinepistol",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_MACHINEPISTOL",
            ammoType: "SMGAMMO"
        },
        ["weapon_minismg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MINISMG */]: {
            type: "weapon_minismg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MINISMG */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "minismg.svg",
            render: "minismg.svg",
            name: "minismg",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_MINISMG",
            ammoType: "SMGAMMO"
        },
        ["weapon_raycarbine" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RAYCARBINE */]: {
            type: "weapon_raycarbine" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RAYCARBINE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "raycarbine.svg",
            render: "raycarbine.svg",
            name: "raycarbine",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "SMGAMMO"
        },
        ["weapon_pumpshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN */]: {
            type: "weapon_pumpshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "pumpshotgun.svg",
            render: "pumpshotgun.svg",
            name: "pumpshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_pumpshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_pumpshotgun_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN_MK2 */]: {
            type: "weapon_pumpshotgun_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN_MK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "pumpshotgunmk2.svg",
            render: "pumpshotgunmk2.svg",
            name: "pumpshotgunmk2",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_pumpshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_sawnoffshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SAWNOFFSHOTGUN */]: {
            type: "weapon_sawnoffshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SAWNOFFSHOTGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "sawnoffshotgun.svg",
            render: "sawnoffshotgun.svg",
            name: "sawnoffshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_sawnoff",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_assaultshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTSHOTGUN */]: {
            type: "weapon_assaultshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTSHOTGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultshotgun.svg",
            render: "assaultshotgun.svg",
            name: "assaultshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_bullpupshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPSHOTGUN */]: {
            type: "weapon_bullpupshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPSHOTGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpupshotgun.svg",
            render: "bullpupshotgun.svg",
            name: "bullpupshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_bullpupshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_mukset" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MUKSET */]: {
            type: "weapon_mukset" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MUKSET */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "musket.svg",
            render: "musket.svg",
            name: "musket",
            description: "",
            count: 1,
            weight: 4.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_musket",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_heavyshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSHOTGUN */]: {
            type: "weapon_heavyshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSHOTGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "heavyshotgun.svg",
            render: "heavyshotgun.svg",
            name: "heavyshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_heavyshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_dbshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_DBSHOTGUN */]: {
            type: "weapon_dbshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_DBSHOTGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "dbshotgun.svg",
            render: "dbshotgun.svg",
            name: "dbshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_autoshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_AUTOSHOTGUN */]: {
            type: "weapon_autoshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_AUTOSHOTGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "autoshotgun.svg",
            render: "autoshotgun.svg",
            name: "autoshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_combatshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATSHOTGUN */]: {
            type: "weapon_combatshotgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATSHOTGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "combatshotgun.svg",
            render: "combatshotgun.svg",
            name: "combatshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        ["weapon_assaultrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE */]: {
            type: "weapon_assaultrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultrifle.svg",
            render: "assaultrifle.svg",
            name: "assaultrifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_assaultrifle_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE_MK2 */]: {
            type: "weapon_assaultrifle_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE_MK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultriflemk2.svg",
            render: "assaultriflemk2.svg",
            name: "assaultriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_carbinerifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE */]: {
            type: "weapon_carbinerifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "carbinerifle.svg",
            render: "carbinerifle.svg",
            name: "carbinerifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_carbinerifle_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE_MK2 */]: {
            type: "weapon_carbinerifle_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE_MK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "carbineriflemk2.svg",
            render: "carbineriflemk2.svg",
            name: "carbineriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_advancedrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ADVANCEDRIFLE */]: {
            type: "weapon_advancedrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ADVANCEDRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "advancedrifle.svg",
            render: "advancedrifle.svg",
            name: "advancedrifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_advancedrifle",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_specialcarbine" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE */]: {
            type: "weapon_specialcarbine" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "specialcarbine.svg",
            render: "specialcarbine.svg",
            name: "specialcarbine",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_specialcarbine",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_specialcarbine_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE_MK2 */]: {
            type: "weapon_specialcarbine_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE_MK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "specialcarbinemk2.svg",
            render: "specialcarbinemk2.svg",
            name: "specialcarbinemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_specialcarbine",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_bullpuprifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE */]: {
            type: "weapon_bullpuprifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpuprifle.svg",
            render: "bullpuprifle.svg",
            name: "bullpuprifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_bullpuprifle",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_bullpuprifle_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE_MK2 */]: {
            type: "weapon_bullpuprifle_mk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE_MK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpupriflemk2.svg",
            render: "bullpupriflemk2.svg",
            name: "bullpupriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_bullpuprifle",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_compactrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMPACTRIFLE */]: {
            type: "weapon_compactrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMPACTRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "compactrifle.svg",
            render: "compactrifle.svg",
            name: "compactrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_militaryrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MILITARYRIFLE */]: {
            type: "weapon_militaryrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MILITARYRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "militaryrifle.svg",
            render: "militaryrifle.svg",
            name: "militaryrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_heavyrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYRIFLE */]: {
            type: "weapon_heavyrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "heavyrifle.svg",
            render: "heavyrifle.svg",
            name: "heavyrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_tacticalrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TACTICALRIFLE */]: {
            type: "weapon_tacticalrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TACTICALRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "tacticalrifle.svg",
            render: "tacticalrifle.svg",
            name: "tacticalrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        ["weapon_mg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MG */]: {
            type: "weapon_mg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MG */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "mg.svg",
            render: "mg.svg",
            name: "mg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_mg_mg",
            ammoType: "LMGAMMO"
        },
        ["weapon_combatmg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATMG */]: {
            type: "weapon_combatmg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATMG */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "combatmg.svg",
            render: "combatmg.svg",
            name: "combatmg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_mg_combatmg",
            ammoType: "LMGAMMO"
        },
        ["weapon_combatmgmk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATMGMK2 */]: {
            type: "weapon_combatmgmk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMBATMGMK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "combatmgmk2.svg",
            render: "combatmgmk2.svg",
            name: "combatmgmk2",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_mg_combatmg",
            ammoType: "LMGAMMO"
        },
        ["weapon_gusenberg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GUSENBERG */]: {
            type: "weapon_gusenberg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GUSENBERG */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "gusenberg.svg",
            render: "gusenberg.svg",
            name: "gusenberg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sb_gusenberg",
            ammoType: "LMGAMMO"
        },
        ["weapon_sniperrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SNIPERRIFLE */]: {
            type: "weapon_sniperrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SNIPERRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "sniperrifle.svg",
            render: "sniperrifle.svg",
            name: "sniperrifle",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sr_sniperrifle",
            ammoType: "SNIPERAMMO"
        },
        ["weapon_heavysniper" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPER */]: {
            type: "weapon_heavysniper" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "heavysniper.svg",
            render: "heavysniper.svg",
            name: "heavysniper",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sr_heavysniper",
            ammoType: "SNIPERAMMO"
        },
        ["weapon_heavysnipermk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPERMK2 */]: {
            type: "weapon_heavysnipermk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPERMK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "heavysnipermk2.svg",
            render: "heavysnipermk2.svg",
            name: "heavysnipermk2",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sr_heavysniper",
            ammoType: "SNIPERAMMO"
        },
        ["weapon_marksmanrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLE */]: {
            type: "weapon_marksmanrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanrifle.svg",
            render: "marksmanrifle.svg",
            name: "marksmanrifle",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        ["weapon_marksmanriflemk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLEMK2 */]: {
            type: "weapon_marksmanriflemk2" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLEMK2 */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanriflemk2.svg",
            render: "marksmanriflemk2.svg",
            name: "marksmanriflemk2",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        ["weapon_precisionrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PRECISIONRIFLE */]: {
            type: "weapon_precisionrifle" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PRECISIONRIFLE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "precisionrifle.svg",
            render: "precisionrifle.svg",
            name: "precisionrifle",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        ["weapon_compactlauncher" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMPACTLAUNCHER */]: {
            type: "weapon_compactlauncher" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_COMPACTLAUNCHER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "compactlauncher.svg",
            render: "compactlauncher.svg",
            name: "compactlauncher",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        ["weapon_firework" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_FIREWORK */]: {
            type: "weapon_firework" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_FIREWORK */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "firework.svg",
            render: "firework.svg",
            name: "firework",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_lr_firework",
            ammoType: ""
        },
        ["weapon_grenadelaunchersmoke" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHERSMOKE */]: {
            type: "weapon_grenadelaunchersmoke" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHERSMOKE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "granadelaunchersmoke.svg",
            render: "granadelaunchersmoke.svg",
            name: "granadelaunchersmoke",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        ["weapon_grenadelauncher" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHER */]: {
            type: "weapon_grenadelauncher" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "grenadelauncher.svg",
            render: "grenadelauncher.svg",
            name: "grenadelauncher",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        ["weapon_hominglauncher" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HOMINGLAUNCHER */]: {
            type: "weapon_hominglauncher" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HOMINGLAUNCHER */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "hominglauncher.svg",
            render: "hominglauncher.svg",
            name: "hominglauncher",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_lr_homing",
            ammoType: ""
        },
        ["weapon_minigun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MINIGUN */]: {
            type: "weapon_minigun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MINIGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "minigun.svg",
            render: "minigun.svg",
            name: "minigun",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_mg_minigun",
            ammoType: ""
        },
        ["weapon_railgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RAILGUN */]: {
            type: "weapon_railgun" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RAILGUN */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "railgun.svg",
            render: "railgun.svg",
            name: "railgun",
            description: "",
            count: 1,
            weight: 6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ar_railgun",
            ammoType: ""
        },
        ["weapon_rpg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RPG */]: {
            type: "weapon_rpg" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RPG */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "rpg.svg",
            render: "rpg.svg",
            name: "rpg",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_lr_rpg",
            ammoType: ""
        },
        ["weapon_ball" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BALL */]: {
            type: "weapon_ball" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BALL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "ball.svg",
            render: "ball.svg",
            name: "ball",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_golf_ball"
        },
        ["weapon_bzgas" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BZGAS */]: {
            type: "weapon_bzgas" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BZGAS */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "bzgas.svg",
            render: "bzgas.svg",
            name: "bzgas",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_gas_grenade"
        },
        ["weapon_smokegrenade" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SMOKEGRENADE */]: {
            type: "weapon_smokegrenade" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SMOKEGRENADE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "smokegrenade.svg",
            render: "smokegrenade.svg",
            name: "smokegrenade",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_gas_grenade"
        },
        ["weapon_flare" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_FLARE */]: {
            type: "weapon_flare" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_FLARE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "flare.svg",
            render: "flare.svg",
            name: "flare",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_am_flare"
        },
        ["weapon_grenade" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GRENADE */]: {
            type: "weapon_grenade" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GRENADE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "grenade.svg",
            render: "grenade.svg",
            name: "grenade",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ex_grenadefrag"
        },
        ["weapon_molotov" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MOLOTOV */]: {
            type: "weapon_molotov" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MOLOTOV */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "molotov.svg",
            render: "molotov.svg",
            name: "molotov",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ex_molotov"
        },
        ["weapon_proximitymine" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PROXIMITYMINE */]: {
            type: "weapon_proximitymine" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PROXIMITYMINE */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "proximymine.svg",
            render: "proximymine.svg",
            name: "proximymine",
            description: "",
            count: 1,
            weight: 12,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ex_apmine"
        },
        ["weapon_pipebomb" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PIPEBOMB */]: {
            type: "weapon_pipebomb" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PIPEBOMB */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "pipebomb.svg",
            render: "pipebomb.svg",
            name: "pipebomb",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_bomb_01_s"
        },
        ["weapon_snowball" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SNOWBALL */]: {
            type: "weapon_snowball" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SNOWBALL */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "snowball.svg",
            render: "snowball.svg",
            name: "snowball",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_ex_snowball"
        },
        ["weapon_stickybomb" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_STICKYBOMB */]: {
            type: "weapon_stickybomb" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_STICKYBOMB */,
            typeCategory: 2 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON */,
            hash: "",
            key: "",
            quality: 0,
            image: "stickybomb.svg",
            render: "stickybomb.svg",
            name: "stickybomb",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_bomb_01_s"
        },
        ["pistol_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PISTOLAMMO */]: {
            type: "pistol_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PISTOLAMMO */,
            typeCategory: 3 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_AMMO */,
            hash: "",
            key: "",
            quality: 0,
            image: "pistol_ammo.svg",
            render: "pistol_ammo.svg",
            name: "Pistol Ammo",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 60,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_box_ammo01a"
        },
        ["smg_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SMGAMMO */]: {
            type: "smg_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SMGAMMO */,
            typeCategory: 3 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_AMMO */,
            hash: "",
            key: "",
            quality: 0,
            image: "smg_ammo.svg",
            render: "smg_ammo.svg",
            name: "SMG Ammo",
            description: "Ammunition to be used on Sub Machine Guns",
            count: 1,
            weight: 1,
            maxStack: 60,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_box_ammo01a"
        },
        ["shotgun_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SHOTGUNAMMO */]: {
            type: "shotgun_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SHOTGUNAMMO */,
            typeCategory: 3 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_AMMO */,
            hash: "",
            key: "",
            quality: 0,
            image: "shotgun_ammo.svg",
            render: "shotgun_ammo.svg",
            name: "Shotgun Ammo",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 30,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_box_ammo01a"
        },
        ["mg_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MGAMMO */]: {
            type: "mg_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MGAMMO */,
            typeCategory: 3 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_AMMO */,
            hash: "",
            key: "",
            quality: 0,
            image: "mg_ammo.svg",
            render: "mg_ammo.svg",
            name: "Machine Gun Ammo",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 100,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_box_ammo01a"
        },
        ["rifle_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RIFLEAMMO */]: {
            type: "rifle_ammo" /* RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_RIFLEAMMO */,
            typeCategory: 3 /* RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_AMMO */,
            hash: "",
            key: "",
            quality: 0,
            image: "rifle_ammo.svg",
            render: "rifle_ammo.svg",
            name: "Rifle Ammo",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 100,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "prop_box_ammo01a"
        }
    };
})(inventoryAssets || (exports.inventoryAssets = inventoryAssets = {}));
